version: "3"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=your@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  genshin-backend:
    image: ghcr.io/annisa-rachma/genshin-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.genshin-api.rule=Host(`api.genshin.annisarachma.com`)"
      - "traefik.http.routers.genshin-api.entrypoints=websecure"
      - "traefik.http.routers.genshin-api.tls.certresolver=myresolver"
