services:
  genshin-backend:
    image: ghcr.io/annisa-rachma/genshin-backend:latest
    container_name: genshin-backend
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.genshin-api.rule=Host(`api.genshin.annisarachma.com`)"
      - "traefik.http.routers.genshin-api.entrypoints=websecure"
      - "traefik.http.routers.genshin-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.genshin-api.loadbalancer.server.port=4000"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
